### PR TITLE
Improve performance of the quoters

### PR DESCRIPTION
**Pull request by bdraco**
same change as https://github.com/aio-libs/aiohttp/pull/9603

### CODE REVIEW

**Comment by bdraco** [comment]
Looks like its already better optimized here

**Review by asvetlov — COMMENTED** [review]
Could you please postpone the merge until tomorrow. I'd like to dig in deeper a little

**Comment by bdraco** [comment]
This one didn't show enough performance change to make it worth it.

https://github.com/aio-libs/aiohttp/pull/9603 does though. Already left a note there that it needs a "second set of 👀"

**Comment by asvetlov** [comment]
Well, I've looked on Cython generated code. 
Fast path (when a error is not raised) is equally fast for both versions.
Error path shouldn't be optimized at all, a chance to get out-of-memory error is negligible. It should be processed, sure; but spending time to optimize it doesn't make sense.

**Comment by bdraco** [comment]
I agree, that's why I closed this one

**Pull request closed without merging**
