### PR TITLE
🧪 Collect Cython coverage in CI

### PR DESCRIPTION
**Pull request by webknjaz**
$sbj.

### CODE REVIEW

**Comment by webknjaz** [comment]
@mjpieters @Dreamsorcerer does the change note sound comprehensive enough? https://yarl--961.org.readthedocs.build/en/961/changes/#contributor-facing-changes

**Comment by Dreamsorcerer** [comment]
Yep, nice.

**Review by Dreamsorcerer — APPROVED** [review]

**Comment by webknjaz** [comment]
PyPy is failing because coveragepy loads the cython plugin and emits a warning: https://github.com/nedbat/coveragepy/issues/1702. I think I'll just stick a `sed` in there...

**Comment by webknjaz** [comment]
Postponing merging since Coverage.py is unable to map non-editable install lines to the source: it reports 0 lines and 100% coverage. Need to investigate.

**Comment by Dreamsorcerer** [comment]
While I have your attention, are you happy with adding bdraco to committers?
https://github.com/aio-libs/aiohttp/pull/7865#issuecomment-1823422057

**Comment by webknjaz** [comment]
> While I have your attention, are you happy with adding bdraco to committers? [aio-libs/aiohttp#7865 (comment)](https://github.com/aio-libs/aiohttp/pull/7865#issuecomment-1823422057)

Yeah, I meant to respond. Sorry. I'm all for it! Could you make a separate issue for transparency, though? Maybe, tag some active folks across the org? @mjpieters somes to mind. Here are the previous examples: https://github.com/aio-libs/aiohttp/issues?q=is%3Aissue+sort%3Aupdated-desc+Nominate.

**Comment by webknjaz** [comment]
Apparently, I forgot to pass the same cython directives to the bare `cython` call as I set in the build backend.

**Comment by webknjaz** [comment]
FTR this change revealed that parts of the tests aren't being executed.

**Pull request merged**
