### PR TITLE
Allow scheme replacement for relative urls

### PR DESCRIPTION
**Pull request by mikenemkov**

### CODE REVIEW

**Comment by kxepal** [comment]
What's the case for that? Relative URL are relative because of that. With schema they becomes absolute and not always valid due to schema requirements. For instance, value in test `"http:///path/to"` is not valid HTTP URL, but we're make it feels like ok.

**Comment by kxepal** [comment]
What's the case for that? Relative URL are relative because of that. With schema they becomes absolute and not always valid due to schema requirements. For instance, value in test `"http:///path/to"` is not valid HTTP URL, but we're make it feels like ok.

**Comment by asvetlov** [comment]
Currently on my job we use yarl with non-standard schemas like `storage:`, `user:`, `job:` etc.
I've found that yarl restrictions are too tight somewhere (while I personally was the author of these limitations).
Sometimes we reconstruct `URL` from a string as a workaround.

**Comment by asvetlov** [comment]
I'll merge it with changelog update.

**Comment by kxepal** [comment]
> Currently on my job we use yarl with non-standard schemas like `storage:`, `user:`, `job:` etc.

This case is good, but will it produce valid results for them? Current test shows that it sets empty authority, but at the same time it's optional part of URL which shouldn't be present for `maitto`, `news`, `tel` and more else schemas.

**Pull request closed without merging**
