### PR TITLE
Fix quoting

### LINKED ISSUE #41: Core dump
`yarl.URL('j\x1a\udcf4q\udcda/\udc97g\udcee\udccb\x0ch\udccb\x18\udce4v\x1b\udce2\udcce\udccecom/y\udccepj\x16')`

### LINKED ISSUE #43: tmpbuf - compiling error
Hello,

I get this compiling error:

`sudo pip3 install yarl
Downloading/unpacking yarl
  Downloading yarl-0.8.1.tar.gz (121kB): 121kB downloaded
  Running setup.py (path:/tmp/pip-build-nm8vbb7v/yarl/setup.py) egg_info for package yarl
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            if ch in ALLOWED:
                PyUnicode_WriteChar(ret, ret_idx, ch)
                ret_idx +=1
                continue
    
            tmpbuf = PyUnicode_AsUTF8AndSize(ch, &tmpbuf_size)
                  ^
    ------------------------------------------------------------
    
    yarl/_quoting.pyx:117:15: Assignment to non-lvalue 'tmpbuf'
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-nm8vbb7v/yarl/setup.py", line 27, in <module>
        extensions = cythonize(extensions)
      File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 840, in cythonize
        cythonize_one(*args[1:])
      File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 959, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: yarl/_quoting.pyx
    Compiling yarl/_quoting.pyx because it changed.
    Cythonizing yarl/_quoting.pyx
    Complete output from command python setup.py egg_info:
    

Error compiling Cython file:

------------------------------------------------------------

...

        if ch in ALLOWED:

            PyUnicode_WriteChar(ret, ret_idx, ch)

            ret_idx +=1

            continue

        tmpbuf = PyUnicode_AsUTF8AndSize(ch, &tmpbuf_size)

              ^

------------------------------------------------------------

yarl/_quoting.pyx:117:15: Assignment to non-lvalue 'tmpbuf'

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-nm8vbb7v/yarl/setup.py", line 27, in <module>

    extensions = cythonize(extensions)

  File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 840, in cythonize

    cythonize_one(*args[1:])

  File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 959, in cythonize_one

    raise CompileError(None, pyx_file)

Cython.Compiler.Errors.CompileError: yarl/_quoting.pyx

Compiling yarl/_quoting.pyx because it changed.

Cythonizing yarl/_quoting.pyx

----------------------------------------
`

### PR DESCRIPTION
**Pull request by mosquito**
Fix #41 
Fix #43

### CODE REVIEW

**Comment by mosquito** [comment]
Hi there. Please rewiew.

**Comment by fafhrd91** [comment]
Super! Thanks!

**Comment by mosquito** [comment]
Can you upload a new release?

**Comment by fafhrd91** [comment]
yes, will do.

**Pull request merged**
