### PR TITLE
add `/` to protected chars in `_QUERY_REQUOTER`

### PR DESCRIPTION
**Pull request by SafaSafari**
## What do these changes do?

this patch will fix query reqouter skip chars

## Are there changes in behavior for the user?

who users cannot download Instagram posts using aiohttp, after this patch will can =))

## Related issue number

actually no, but I'm wondering why it's not =))

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Review by webknjaz — CHANGES_REQUESTED** [review]
I would be curious to see a quote from the standard that this attempts to comply with, and some explanation of what  doesn't work. With reproducers et al.

If this change is correct indeed, the PR will also need a test covering this specific case. And finally, the linting violations will have to be corrected.

Unfortunately, without understanding of what this patch attempts to fix and what the side effects would be, we can't accept this pull request in its current state.

@SafaSafari could you address the above shortcomings and provide us with all the information necessary to proceed?

**Comment by SafaSafari** [comment]
https://github.com/aio-libs/yarl/assets/29104726/80150edd-0905-47f0-b018-05d3dd06510a

this is what actually occurred and that's my fix for that

also i think linter failed to check because of ` character in CHANGES rst file
@webknjaz

**Comment by webknjaz** [comment]
The video doesn't show the actual URL original, nor can copy it. So it can't be verified.

Besides, the earlier points regarding the low quality and missing bits in the patch still stand.

But if I were to make a wild guess, you're probably hitting reencoding on redirects: https://github.com/aio-libs/aiohttp/issues/5319#issuecomment-1182513707. Using proper arguments (as in, `requote_redirect_url=False`) is the right way to solve this. Also, passing pre-built yarl objects to aiohttp can give more control for the initial input.
This is definitely not a bug. Not in yarl.

**Comment by webknjaz** [comment]
Closing per above.

**Pull request closed without merging**
