### PR TITLE
Fixed some Coverage issues.

### PR DESCRIPTION
**Pull request by AraHaan**
This should fix some coverage partials (2) and the single miss on this library.

### CODE REVIEW

**Comment by AraHaan** [comment]
The remaining partials I would need help with fixing as it is sorta hard to read to get what I need to do to ensure the other case of the partials are met.

**Comment by AraHaan** [comment]
oh great I do not know how I could fix the last 2 issues. There is got to be a clue for those. hmm

**Comment by AraHaan** [comment]
@asvetlov, @fafhrd91 have any idea why my additions to tests on test_quoting.py seem to not fix the remaining partials?

**Comment by AraHaan** [comment]
@fafhrd91 mind looking into why the 2 partials left are not resolving currently and how I could fix the tests for those to make them resolve?

**Comment by asvetlov** [comment]
Cool! Thank you!

**Comment by AraHaan** [comment]
yw

**Pull request merged**
