### PR TITLE
Allow user=None in URL.build and sync .pyi with source.

### PR DESCRIPTION
**Pull request by blazewicz**
## What do these changes do?

Fix type-check warnings when passing `Optional` arguments to URL.build.

## Are there changes in behavior for the user?

Changes related only to static type checking.

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is `<Name> <Surname>`.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Comment by asvetlov** [comment]
What is the difference between `user=None` and currently supported `user=""`.
Why empty string doesn't work for you?

**Comment by blazewicz** [comment]
There is simply no need to use empty string as default value. Value of this parameter is checked and replaced in `URL._make_netloc` anyway. 

In my case I use `os.getenv()` to get paramters from environment and if variable is not set it returns None - it is very common to use `None` for unassigned values, for example `.get()` method of dict-like objects.

Use of `None` is generaly more lightweight and faster as it uses reference to built-in object instead of creating new object.

**Comment by asvetlov** [comment]
You may be surprised but the empty string has the same caching strategy as `None`, so performance is basically the same.

Nonetheless, agree with the PR.

**Comment by blazewicz** [comment]
> You may be surprised but the empty string has the same caching strategy as None, so performance is basically the same.

Probably true, I won't argue on that.

Should I squash commits?

**Comment by asvetlov** [comment]
No, the project uses GitHub "Squash and merge" button.

**Comment by asvetlov** [comment]
thanks!

**Pull request merged**
